# Generated by Django 5.2 on 2025-05-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('manager', 'manager'), ('Pl', 'Productledear'), ('product_manager', 'PM'), ('MD', 'MD')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiAPP.company')),
            ],
        ),
    ]
